{% set name = "napari-ism" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-ISM-{{ version }}.tar.gz
  sha256: 299516bdeeffb4fd7903c3e76820a7bfd4569a69a54060314f50eaec7ca545ef
  patches:
    - qtpy.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - brighteyes-ism >=1.2.2
    - h5py
    - magicgui
    - matplotlib-base
    - napari
    - napari-plugin-engine
    - numpy
    - python >={{ python_min }}
    - qtpy
    - scipy

test:
  imports:
    - napari_ism
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-ISM
  summary: It performs Adaptive Pixel Reassignment.
  license: LGPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/VicidominiLab/napari-ISM

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
